---
- name: Install Nginx on Ubuntu
  hosts: web_servers
  user: ubuntu
  # connection: local
  become: yes
  become_method: sudo  # To escalate privileges for package installation
  
  roles:
    - install-dependencies
    - install-nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted